# Generated by Django 4.2.8 on 2023-12-21 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2023, 12, 22, 0, 49, 23, 680713), verbose_name='дата последнего посещения'),
        ),
    ]
