# Generated by Django 4.2.8 on 2023-12-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место выполнения')),
                ('time', models.CharField(max_length=150, verbose_name='время выполнения')),
                ('action', models.TextField(max_length=700, verbose_name='действие')),
                ('usefulness', models.BooleanField(default=False, verbose_name='полезность')),
                ('connectivity', models.BooleanField(default=False, verbose_name='связанность')),
                ('frequency', models.CharField(max_length=150, verbose_name='переодичность')),
                ('duration', models.IntegerField(verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичность')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
