# Generated by Django 4.2.8 on 2024-01-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место выполнения')),
                ('time', models.CharField(max_length=150, verbose_name='время выполнения')),
                ('action', models.TextField(max_length=700, verbose_name='действие')),
                ('usefulness', models.BooleanField(default=False, verbose_name='полезность')),
                ('pleasantness', models.BooleanField(default=False, verbose_name='приятность')),
                ('frequency', models.CharField(choices=[('once every three hours', 'once every three hours'), ('twice a day', 'twice a day'), ('once a day', 'once a day'), ('once every two days', 'once every two days'), ('once every three days', 'once every three days'), ('once every four days', 'once every four days'), ('once every five days', 'once every five days'), ('once every six days', 'once every six days')], max_length=150, verbose_name='переодичность')),
                ('duration', models.IntegerField(verbose_name='время на выполнение в минутах')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичность')),
                ('award', models.CharField(blank=True, default='', max_length=150, verbose_name='вознаграждение')),
                ('connectivity', models.ManyToManyField(default=None, to='useful_habits.habit', verbose_name='связанные привычки')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
