# Generated by Django 4.2.8 on 2023-12-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='award',
            field=models.CharField(default=None, max_length=150, verbose_name='вознаграждение'),
        ),
        migrations.AddField(
            model_name='habit',
            name='pleasantness',
            field=models.BooleanField(default=False, verbose_name='приятность'),
        ),
        migrations.RemoveField(
            model_name='habit',
            name='connectivity',
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.IntegerField(verbose_name='время на выполнение в минутах'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('once every three hours', 'once every three hours'), ('twice a day', 'twice a day'), ('once a day', 'once a day'), ('once every two days', 'once every two days'), ('once every three days', 'once every three days'), ('once every four days', 'once every four days'), ('once every five days', 'once every five days'), ('once every six days', 'once every six days')], max_length=150, verbose_name='переодичность'),
        ),
        migrations.AddField(
            model_name='habit',
            name='connectivity',
            field=models.ManyToManyField(default=False, to='useful_habits.habit', verbose_name='связанные привычки'),
        ),
    ]
