# Generated by Django 4.2.8 on 2023-12-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0003_habit_award_habit_pleasantness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='award',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='вознаграждение'),
        ),
    ]
