# Generated by Django 4.2.8 on 2023-12-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0004_alter_habit_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='award',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='вознаграждение'),
        ),
    ]
